plugins:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-sequel

Layout/IndentationStyle:
  EnforcedStyle: tabs
Layout/IndentationWidth:
  Width: 1
Layout/LineLength:
  Max: 100
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent
Layout/FirstParameterIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/MultilineArrayBraceLayout:
  EnforcedStyle: new_line
Layout/MultilineHashBraceLayout:
  EnforcedStyle: new_line

## https://github.com/JuanitoFatas/fast-ruby/issues/123
Performance/Casecmp:
  Enabled: false

RSpec/NestedGroups:
  Max: 5
RSpec/DescribeClass:
  Exclude:
    - spec/gorilla_patch/inflections/dry_inflector_spec.rb
    - spec/gorilla_patch/inflections/sequel_spec.rb

Metrics/BlockLength:
  AllowedMethods:
    - refine
  Exclude:
    - '*.gemspec'
    - spec/**/*.rb

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
