Layout/Tab:
  Enabled: false
Layout/IndentationWidth:
  Width: 1

Metrics/BlockLength:
  ExcludedMethods:
    - refine
  Exclude:
    - 'spec/**/*.rb'

Style/SymbolProc:
  Exclude:
    # Bug in Ruby 2.3: https://bugs.ruby-lang.org/issues/12638
    - 'lib/gorilla_patch/deep_dup.rb'

Performance/Casecmp:
  ## https://github.com/rubocop-hq/rubocop/issues/4277
  Enabled: false

AllCops:
  TargetRubyVersion: 2.3
