Layout/Tab:
  Enabled: false
Layout/IndentationWidth:
  Width: 1
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  ExcludedMethods:
    - refine
  Exclude:
    - 'spec/**/*.rb'

AllCops:
  TargetRubyVersion: 2.4
