language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5

before_install:
  - gem update --system
  ## https://github.com/travis-ci/travis-ci/issues/8978#issuecomment-377680126
  - gem install bundler

cache: bundler

notifications:
  email:
    on_success: change
